# Generated by Django 2.1.5 on 2019-02-09 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20190205_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_like',
            field=models.ManyToManyField(related_name='post_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
