# Generated by Django 2.1.5 on 2019-02-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='count',
        ),
    ]
