# Generated by Django 2.1.5 on 2019-02-24 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_auto_20190213_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='account',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='post_like',
            field=models.ManyToManyField(related_name='post_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(help_text='최대 150자 입력 가능', max_length=150),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
